version: '2.3'
services:
  jupyter:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    image: "guti1/drlnd"
    ports:
      - "8888:8888"
    volumes:
      - .:/tf
    command: [ "sh", "-c",
               "jupyter-lab --ip 0.0.0.0 --port 8888 --allow-root --LabApp.token=''"]
  jupyter-gpu:
    build:
      context: ./Docker
      dockerfile: Dockerfile-GPU
    image: "guti1/drlnd-gpu"
    runtime: nvidia
    ports:
      - "8888:8888"
    volumes:
      - .:/tf
    command: [ "sh", "-c",
                "xvfb-run -s '-screen 0 1400x900x24' jupyter-lab --ip 0.0.0.0 --port 8888 --allow-root --LabApp.token=''"]
  debug:
    build:
      context: ./Docker
      dockerfile: Dockerfile-debug
    image: "guti1/drlnd-debug"
    volumes:
      - .:/opt/project
    command: [ "sh", "-c"]
